import React, { useState } from 'react';
import { db } from '../services/mockDatabase';
import { CAMPUSES, FACULTIES, Role, SCHOOLS, UserType } from '../types';
import { BookOpen, User, Lock, Building, GraduationCap, MapPin, HelpCircle } from 'lucide-react';

interface AuthProps {
  onLogin: () => void;
  onNavigateManual: () => void;
}

const Auth: React.FC<AuthProps> = ({ onLogin, onNavigateManual }) => {
  const [isLogin, setIsLogin] = useState(true);
  
  // Login State
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');

  // Register State
  const [regName, setRegName] = useState('');
  const [regEmail, setRegEmail] = useState('');
  const [regPass, setRegPass] = useState('');
  const [regConfirmPass, setRegConfirmPass] = useState('');
  const [regRole, setRegRole] = useState<Role>(Role.RESEARCHER);
  const [regType, setRegType] = useState<UserType>(UserType.STUDENT);
  const [regCampus, setRegCampus] = useState(CAMPUSES[0]);
  const [regFaculty, setRegFaculty] = useState(FACULTIES[0]);

  const handleLogin = (e: React.FormEvent) => {
    e.preventDefault();
    const user = db.login(email, password);
    if (user) {
      onLogin();
    } else {
      setError('อีเมลหรือรหัสผ่านไม่ถูกต้อง');
    }
  };

  const handleRegister = (e: React.FormEvent) => {
    e.preventDefault();
    if (regPass !== regConfirmPass) {
      setError('รหัสผ่านไม่ตรงกัน');
      return;
    }
    
    db.register({
      id: '', // Generated by db
      name: regName,
      email: regEmail,
      password: regPass,
      role: regRole,
      type: regRole === Role.RESEARCHER ? regType : undefined,
      campus: regCampus,
      faculty: regRole === Role.RESEARCHER || regRole === Role.ADVISOR ? regFaculty : undefined,
    });

    alert('ลงทะเบียนสำเร็จ กรุณาเข้าสู่ระบบ');
    setIsLogin(true);
    setError('');
  };

  return (
    <div className="min-h-screen bg-slate-100 flex items-center justify-center p-4">
      {/* Help Button Absolute */}
      <button 
        onClick={onNavigateManual}
        className="fixed top-4 right-4 bg-white text-blue-600 px-4 py-2 rounded-full shadow-md hover:shadow-lg transition-all flex items-center gap-2 text-sm font-medium z-50"
      >
        <HelpCircle size={18} /> คู่มือการใช้งาน
      </button>

      <div className="bg-white rounded-2xl shadow-xl w-full max-w-4xl overflow-hidden flex flex-col md:flex-row">
        
        {/* Left Side: Brand */}
        <div className="md:w-1/2 bg-blue-700 p-10 flex flex-col justify-center text-white relative">
          <div className="absolute top-0 left-0 w-full h-full opacity-10 bg-[url('https://www.transparenttextures.com/patterns/cubes.png')]"></div>
          <div className="z-10">
            <div className="w-16 h-16 bg-white rounded-2xl flex items-center justify-center mb-6 text-blue-700 font-bold text-3xl shadow-lg">T</div>
            <h1 className="text-3xl font-bold mb-2">TNSU-REC</h1>
            <p className="text-blue-100 text-lg mb-8">ระบบจริยธรรมการวิจัยในมนุษย์<br/>มหาวิทยาลัยการกีฬาแห่งชาติ</p>
            <div className="space-y-4 text-sm text-blue-200">
               <div className="flex items-center gap-2">
                 <div className="w-1.5 h-1.5 rounded-full bg-blue-300"></div>
                 <span>ยื่นขอใบรับรองจริยธรรมออนไลน์</span>
               </div>
               <div className="flex items-center gap-2">
                 <div className="w-1.5 h-1.5 rounded-full bg-blue-300"></div>
                 <span>ติดตามสถานะแบบ Real-time</span>
               </div>
               <div className="flex items-center gap-2">
                 <div className="w-1.5 h-1.5 rounded-full bg-blue-300"></div>
                 <span>แจ้งเตือนรายงานความก้าวหน้า</span>
               </div>
            </div>
          </div>
        </div>

        {/* Right Side: Form */}
        <div className="md:w-1/2 p-10 py-12">
          <h2 className="text-2xl font-bold text-slate-800 mb-6 text-center">
            {isLogin ? 'เข้าสู่ระบบ' : 'ลงทะเบียนสมาชิกใหม่'}
          </h2>

          {error && (
            <div className="mb-4 p-3 bg-red-50 text-red-600 text-sm rounded-lg border border-red-100 flex items-center gap-2">
              <span className="font-bold">!</span> {error}
            </div>
          )}

          {isLogin ? (
            <form onSubmit={handleLogin} className="space-y-5">
              <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">อีเมล</label>
                <div className="relative">
                  <User className="absolute left-3 top-3 text-slate-400" size={18} />
                  <input
                    type="email"
                    value={email}
                    onChange={e => setEmail(e.target.value)}
                    className="w-full pl-10 pr-4 py-2.5 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all outline-none"
                    placeholder="user@tnsu.ac.th"
                    required
                  />
                </div>
              </div>
              <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">รหัสผ่าน</label>
                <div className="relative">
                  <Lock className="absolute left-3 top-3 text-slate-400" size={18} />
                  <input
                    type="password"
                    value={password}
                    onChange={e => setPassword(e.target.value)}
                    className="w-full pl-10 pr-4 py-2.5 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all outline-none"
                    placeholder="••••••••"
                    required
                  />
                </div>
              </div>
              <button className="w-full bg-blue-600 hover:bg-blue-700 text-white font-semibold py-3 rounded-lg shadow-md hover:shadow-lg transition-all transform active:scale-95">
                เข้าสู่ระบบ
              </button>
              <div className="text-center mt-4">
                 <button type="button" onClick={() => setIsLogin(false)} className="text-sm text-blue-600 hover:underline">
                    ยังไม่มีบัญชี? ลงทะเบียนที่นี่
                 </button>
              </div>
              <div className="mt-8 pt-6 border-t border-slate-100">
                <p className="text-xs text-slate-400 text-center">
                  สำหรับเจ้าหน้าที่ Admin:<br/>
                  Email: admin_rec@tnsu.ac.th / Pass: admin_rec1234
                </p>
              </div>
            </form>
          ) : (
            <form onSubmit={handleRegister} className="space-y-4 max-h-[60vh] overflow-y-auto pr-2">
              {/* Role Selection */}
              <div className="flex gap-4 mb-4">
                 <label className={`flex-1 p-3 border rounded-lg cursor-pointer text-center text-sm font-medium ${regRole === Role.RESEARCHER ? 'bg-blue-50 border-blue-500 text-blue-700' : 'border-slate-200'}`}>
                    <input type="radio" name="role" className="hidden" checked={regRole === Role.RESEARCHER} onChange={() => setRegRole(Role.RESEARCHER)} />
                    ผู้วิจัย
                 </label>
                 <label className={`flex-1 p-3 border rounded-lg cursor-pointer text-center text-sm font-medium ${regRole === Role.ADVISOR ? 'bg-blue-50 border-blue-500 text-blue-700' : 'border-slate-200'}`}>
                    <input type="radio" name="role" className="hidden" checked={regRole === Role.ADVISOR} onChange={() => setRegRole(Role.ADVISOR)} />
                    อาจารย์ที่ปรึกษา
                 </label>
              </div>

              {regRole === Role.RESEARCHER && (
                <div className="mb-4">
                   <label className="block text-sm font-medium text-slate-700 mb-1">สถานะ</label>
                   <select 
                     className="w-full p-2.5 border border-slate-300 rounded-lg"
                     value={regType}
                     onChange={(e) => setRegType(e.target.value as UserType)}
                   >
                     <option value={UserType.STUDENT}>นักศึกษา</option>
                     <option value={UserType.STAFF}>อาจารย์/บุคลากร</option>
                   </select>
                </div>
              )}

              <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">ชื่อ-นามสกุล</label>
                <input type="text" required value={regName} onChange={e => setRegName(e.target.value)} className="w-full p-2.5 border border-slate-300 rounded-lg" />
              </div>
              
              <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">อีเมล</label>
                <input type="email" required value={regEmail} onChange={e => setRegEmail(e.target.value)} className="w-full p-2.5 border border-slate-300 rounded-lg" />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">สังกัด (วิทยาเขต/รร.)</label>
                    <select value={regCampus} onChange={e => setRegCampus(e.target.value)} className="w-full p-2.5 border border-slate-300 rounded-lg text-sm">
                        <optgroup label="วิทยาเขต">
                            {CAMPUSES.map(c => <option key={c} value={c}>{c}</option>)}
                        </optgroup>
                        <optgroup label="โรงเรียนกีฬา">
                            {SCHOOLS.map(c => <option key={c} value={c}>{c}</option>)}
                        </optgroup>
                    </select>
                </div>
                <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">คณะ</label>
                    <select value={regFaculty} onChange={e => setRegFaculty(e.target.value)} className="w-full p-2.5 border border-slate-300 rounded-lg text-sm">
                        {FACULTIES.map(f => <option key={f} value={f}>{f}</option>)}
                    </select>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                 <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">รหัสผ่าน</label>
                    <input type="password" required value={regPass} onChange={e => setRegPass(e.target.value)} className="w-full p-2.5 border border-slate-300 rounded-lg" />
                 </div>
                 <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">ยืนยันรหัสผ่าน</label>
                    <input type="password" required value={regConfirmPass} onChange={e => setRegConfirmPass(e.target.value)} className="w-full p-2.5 border border-slate-300 rounded-lg" />
                 </div>
              </div>

              <button className="w-full bg-blue-600 hover:bg-blue-700 text-white font-semibold py-3 rounded-lg shadow-md mt-4">
                ลงทะเบียน
              </button>
              <div className="text-center mt-2">
                 <button type="button" onClick={() => setIsLogin(true)} className="text-sm text-blue-600 hover:underline">
                    กลับไปหน้าเข้าสู่ระบบ
                 </button>
              </div>
            </form>
          )}
        </div>
      </div>
    </div>
  );
};

export default Auth;